export const START_BOOKS_FETCHING = 'START_BOOKS_FETCHING';
export const STOP_BOOKS_FETCHING = 'STOP_BOOKS_FETCHING';
export const FETCH_BOOKS_SUCCESS = 'FETCH_BOOKS_SUCCESS';
export const FETCH_BOOKS_FAILED = 'FETCH_BOOKS_FAILED';
